namespace: puljam

# replicaCount: 2
replicaCount: 1

##
# topology.kubernetes.io/zone 설정 필요
##

imagePullSecrets:
  - name: regsecret

image:
  repository: ghcr.io/puljam-project/puljam_backend
  pullPolicy: Always
  tag: "latest"
  platform: "linux/amd64"

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1001
  allowPrivilegeEscalation: false
  privileged: false

ingress:
  enabled: true
  className: "traefik"
  hosts:
    - host: api.mya.ong
      paths:
        - path: /
          pathType: Prefix

livenessProbe:
  httpGet:
    path: /
    port: 10002
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

service:
  type: ClusterIP
  port: 10002
  targetPort: 10002

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  # minReplicas: 2
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
# affinity:
#   podAntiAffinity:
#     preferredDuringSchedulingIgnoredDuringExecution:
#     - weight: 100
#       podAffinityTerm:
#         labelSelector:
#           matchExpressions:
#           - key: app.kubernetes.io/name
#             operator: In
#             values:
#             - puljam-devops
#         topologyKey: topology.kubernetes.io/zone

# topologySpreadConstraints:
#   - maxSkew: 1
#     topologyKey: topology.kubernetes.io/zone
#     whenUnsatisfied: ScheduleAnyway
#     labelSelector:
#       matchLabels:
#         app.kubernetes.io/name: puljam-devops
